pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Test') {
            steps {
                sh 'npm install' // Selenium ve diğer bağımlılıkları yükleyin
                sh 'npm install selenium-webdriver'
                sh 'node selenium.js' // Selenium testini çalıştırın
            }
        }
    }
}
